### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by djc** [humenda/isolang-rs#21]
Hi there, I noticed that the last release on crates.io is three years old, while the repo has a bunch of newer activity. Is there a plan to publish a new version soon?

**Comment by humenda** [comment]
I would like to have testers :). I didn't have time recently much for the
project. If you could please test it, especially the serde support, this would
be greatly appreciated!

**Comment by djc** [comment]
What, in particular, should get tested? Looks like you have pretty decent automated tests already, with most of the code covered.

(If you feel more comfortable, I'm happy if you want to add me as a co-maintainer.)

One things that would be nice to have is to commit the generated code to this repo rather than generating it at crate compilation time. We could add a test in CI that the same code is still generated.

**Comment by humenda** [comment]
Hi

Dirkjan Ochtman schrieb am 06.12.2021, 11:52 +0000:
>What, in particular, should get tested? Looks like you have pretty decent automated tests already, with most of the code covered.

Sure, but tests are not really usage. If you have a project in which you have
been running it, I would say let's integrate your changes and I'll make a
release.
Yes, I can make you a co-maintainer, though I would prefer reading the code
before merging to master, if that is fine with you.

Thanks

**Comment by djc** [comment]
Sorry, but for me it is the other way around. I'm submitting changes to your crate to see how much risk I introduce to my projects, for example, here are some things I'm evaluating before adopting your crate:

* Longer compile times from duplicate dependencies
* CI that works well to make sure pull requests don't regress the test suite
* How responsive maintainers are to my pull requests
* If releases are published quickly after useful changes land

Given the limited functionality of this crate, I don't see why further integration should hold up a release. Without a release, I will not be integrating this crate with my projects.

**Comment by humenda** [comment]
I see your points.\
Generally speaking, I will continue maintaining this crate. However, as I am
currently on a longer business trip, I only now start having time to look into
this. This is not really equal to not being responsive :). In either case,
let's aim for a release for Christmas.

**Comment by djc** [comment]
2.1 has been released.
