### ISSUE TITLE
(Optional) Support for diesel?

### ISSUE THREAD

**Issue by dreuter** [humenda/isolang-rs#3]
Hi :)

thanks for this awesome project.

I was wondering, whether you would accept a pull request, that adds [diesel](https://diesel.rs) support (that means `Language` would implement `FromSql` and `ToSql`).

This would be a opt-in implementation. If this does not make sense for you, one can work around this with a wrapper type.

**Comment by humenda** [comment]
Hi

I'm happy to accept a PR adding (optional) Diesel support. Do you plan to
implement that in the near future? If so, I would probably wait with a release
until then.

Thanks

**Comment by dreuter** [comment]
Ok, I have an implementation of this for a wrapper type already ready. I will try to add this as soon as I get home :)

PS: I assume the reasoning behind releasing a 0. version is that the dependencies are still also pre 1.0. Am I right with that assumption? (I am asking since the library seems really stable.)

**Comment by humenda** [comment]
Great that you're looking into this.

No, it wasn't so much about the dependencies, but more about the level of tests
I had run it on. It worked for my use case, but didn't know about others. Given
that you've added Serde support and look into adding Diesel, it would be a good
idea to bump the version to 1.0.

**Comment by dreuter** [comment]
The only problem I see with this is that bumping the dependencies versions should/could probably be considered a breaking change. I think this would not be a problem with `phf` (as it is private, now that I think about it) and also not with `serde` (as it is above 1.0), but if I introduce `diesel` I would probably write a remark in the README, that this feature is not considered stable, until `diesel` reaches 1.0 (which should be soonish).

**Comment by humenda** [comment]
We could also release 0.2 and release 1.0 as soon as Diesel is stable, although
it's not a breaking change in this crate.

**Comment by dreuter** [comment]
It is a breaking change, since if you implement a trait from a external crate and than increase the version number in an incompatible way the type of the implementor changes.

But I think I did read somewhere that the rust community does not treat this as a semver breaking change.

**Comment by dreuter** [comment]
Hi :)

I think we can close this issue. Maybe we should open a new issue about getting to 1.0?

Diesel now has a 1.0 alpha.
