### ISSUE TITLE
Anyway to do country name to IsoCode639 conversion?

### ISSUE THREAD

**Issue by mabushey** [humenda/isolang-rs#31]
It seems like this crate only goes one way. Is there any chance it can be enhanced to convert ie `Russian` -> `RUS`?

Thanks!

**Comment by djc** [comment]
I guess that wouldn't be too hard to add. Would you mind submitting a PR? You'd probably want to update the [code generation test](https://github.com/humenda/isolang-rs/blob/master/tests/generate_static_table.rs) to generate another `phf::Map`; it should be pretty straightforward.

**Comment by mabushey** [comment]
@djc Thanks for your response. I would love to contribute a PR, however when it comes to Rust I'm maybe a step or two past being a complete Noob. I started programming with 8 bit assembly and absolutely love Rust. When I get a chance I'll look at the phf::Map and see if I can figure it out. If you could provide some guidance it would help.

**Comment by djc** [comment]
I'm happy to provide further guidance, but it would probably be useful if you try some things based on what I wrote in my earlier comment and then ask specific questions that you're left with. Like I said, I expect it to be a straightforward task, just a matter of duplicating an existing function and tweaking it a bit to get the desired result.

**Comment by humenda** [comment]
>It seems like this crate only goes one way. Is there any chance it can be enhanced to convert ie `Russian` -> `RUS`?

I took the time and implemented your request in b6e6f20cca4baefca4d. Could you

please test whether this is enough for your purposes. In summary, you can now
use `Language::from_name`, `Language::match_names`, `Language::from_autonym`
and `Language::match_autonyms`, see their docs.
