### ISSUE TITLE
Modern Greek should be Greek

### ISSUE THREAD

**Issue by Dimkar3000** [humenda/isolang-rs#33]
Hello 👋

This is a really useful library and I am trying to use in a project of my own. 

## The use case
 I want to use this library to help me rename some files, to they are compatible with with my Jellyfin installation. Currently I have subtitles folders with names in the form: `Movie_English.srt` and I want to rename them to `Movie.en.srt`. This library is ideal for this.

## The problem
The library `Language::from_name` function expect me to give `Modern Greek` to get the Greek language code. But by all occasion 'Modern Greek' is just 'Greek' (I just happen to be one and notice this😄  )

## Solution
If you want to avoid breaking changes for this, I suggest both "Modern Greek" and "Greek" to map to the same values, otherwise just change it. The autonym field has the value "Ελληνικά" which is means Greek so the translation is correct

**Comment by humenda** [comment]
Hi

Thanks for reaching out.
This is more of a controversial change: isolang relies on data from
<https://iso639-3.sil.org/code_tables/download_tables>. I would like to remain
compatible with the official specification. From a linguistic point of view, I
can see the reason behind having "ancient greek" and "modern greek", though a
native speaker would likely disagree. Is there a chance that you could add a
simple indirection in your application? I.e.

```
fn lookup(s: &str) -> Language {
    if s == "Greek" {
        Language::from_name("Modern Greek")
    } else {
        Language::from_name(s)
    }
}
```

It is possible to add this in ISO lang as well, but I'm reluctant to add an
edge case. Would this be ok for you?

**Comment by humenda** [comment]
Is there still any interest in this? Otherwise I would close the issue.

**Comment by humenda** [comment]
There have not been any more comments on this, so I am closing this issue for the time being. If the demand should be still there, we could reopen the issue and implement this.
