### ISSUE TITLE
Mandarin Chinese dont convert to ISO-639-1

### ISSUE THREAD

**Issue by NullVerdict** [humenda/isolang-rs#41]
This makes sense since it is not in iso-639-1, but can you replace it with zh?

**Comment by humenda** [comment]
Hi

Could you elaborate in which context you see this behaviour? "zh" is actually
the 639-1 code for mandarin Chinese and it's also in the auto-generated
(hidden, internal) table `TWO_TO_THREE`, i.e. `from_639_1` should actually
work for "zh".

**Comment by NullVerdict** [comment]
> Hi Could you elaborate in which context you see this behaviour? "zh" is actually the 639-1 code for mandarin Chinese and it's also in the auto-generated (hidden, internal) table `TWO_TO_THREE`, i.e. `from_639_1` should actually work for "zh".

Ok, i use whichlang for language detection.
To convert iso639-3 to iso639-1 I use this:
```
    let iso639_3_code = format!("{:?}", detected_language);
    let iso639_1_code = Language::from_639_3(&iso639_3_code.to_lowercase()).and_then(|lang| lang.to_639_1());
```
If i try convert Jpn, this works jpn => jp rus => ru, but cmn ≠ zh

639-3 code has 4 codes for language, but 639-1 has only zh


Whiclang has this language list
```
Ara
Cmn
Deu
Eng
Fra
Hin
Ita
Jpn
Kor
Nld
Por
Rus
Spa
Swe
Tur
Vie
```

**Comment by humenda** [comment]
Alright, I see. The issue is that zh is attributed to zho and you're
specifically trying to convert cmn to zh. Wouldn't it be better if you'd add a
synonym for cmn to zho on your side? While I understand your request, I wonder
whether a deviation from the standard would make sense, in particular because
the crate is called `isolang`.

Would zho also include Cantonese?

**Comment by NullVerdict** [comment]
> Alright, I see. The issue is that zh is attributed to zho and you're specifically trying to convert cmn to zh. Wouldn't it be better if you'd add a synonym for cmn to zho on your side? While I understand your request, I wonder whether a deviation from the standard would make sense, in particular because the crate is called `isolang`. Would zho also include Cantonese?

![изображение](https://github.com/humenda/isolang-rs/assets/24498484/adeb43b4-2fe5-41cb-9d73-8aebc609f100)

**Comment by humenda** [comment]
According to Wikipedia, zho is the code for all Chinese languages, not very
useful indeed.

I would imagine it's best to add a "deviations" feature. Another such
deviation from the ISO norm would be `ell` that says `modern Greek` and nobody
today would actually say that — it's Greek.
If you want, you can submit a PR adding this as a feature. Otherwise, I'll try
to have a look in the next days.

**Comment by NullVerdict** [comment]
> According to Wikipedia, zho is the code for all Chinese languages, not very useful indeed. I would imagine it's best to add a "deviations" feature. Another such deviation from the ISO norm would be `ell` that says `modern Greek` and nobody today would actually say that — it's Greek. If you want, you can submit a PR adding this as a feature. Otherwise, I'll try to have a look in the next days.

zho? I use ISO-639-1, there are no more than 2 letters. zho only for ISO-639-2 or ISO-639-3. 

I believe that converting from zho or cmn to zh is correct. After all, ISO-639-1 has only zh for Chinese. Why do I need some zho if I don't have it in ISO-639-1?

**Comment by humenda** [comment]
As far as I understand, there is a standardised and hence obligatory way to
convert from 639-3 to 639-1. And this one lists zho as the long version of zh.
Therefore, it is a deviation to add cmn → zh. It is in any case not an issue
for you, it anyway needs to be implemented and hence I see no real issue to
add this feature. It could probably be a default feature as only few people
would probably want to have the strict version.

**Comment by NullVerdict** [comment]
> As far as I understand, there is a standardised and hence obligatory way to convert from 639-3 to 639-1. And this one lists zho as the long version of zh. Therefore, it is a deviation to add cmn → zh. It is in any case not an issue for you, it anyway needs to be implemented and hence I see no real issue to add this feature. It could probably be a default feature as only few people would probably want to have the strict version.

Wait, what? How's that? Even this library for NodeJS converts cmn to zh

https://www.npmjs.com/package/iso-639-3-to-1

What is the deviation? We are not using ISO-639-2 or ISO-639-3, which have 3 letters, not 2 as in ISO-639-1. What's the problem?

**Comment by humenda** [comment]
>Wait, what? How's that? Even this library for NodeJS converts cmn to zh

I'm basing this library on <https://iso-639-3.sil.org>, the official 639-3
registration site.
It might be that you are correct that 639-1 just knows zh, but then I'd need a
reliable and machine-readable source that converts between 639-3 and 639-1.

The mentioned 639-3 site links to
<http://www.infoterm.info/standardization/iso_639_1_2002.php> but I couldn't
find an official file there for use by isolang-rs. If you find one, please let
me know.

**Comment by NullVerdict** [comment]
> Wait, what? How's that? Even this library for NodeJS converts cmn to zh
> I'm basing this library on <https://iso-639-3.sil.org>, the official 639-3 registration site. It might be that you are correct that 639-1 just knows zh, but then I'd need a reliable and machine-readable source that converts between 639-3 and 639-1. The mentioned 639-3 site links to <http://www.infoterm.info/standardization/iso_639_1_2002.php> but I couldn't find an official file there for use by isolang-rs. If you find one, please let me know.

You mean the .tab and .tsv tables? They can be changed manually, I can convert it to zh all ISO-639-3 codes to ISO-639-1 codes.

**Comment by humenda** [comment]
Sure, changing them manually is always an option. However, I would like to
have a source that I can constantly monitor for changes, i.e. something from
the ISO. If you would find such a table/CSV/etc., I'd be happy to incooperate
it.

**Comment by humenda** [comment]
I've researched the issue a bit again. I don't mind adding a mechanism for
adding zh as an exception. However, I am not sure how to handle the ISO 639-3 to
639-1 conversion issue as zh would then translate both to zho and to cmn. While
I see that mandarin is de facto what people refer to as `zh`, I still think it's
wrong in specific scenarios, where the macro langauge, i.e. all Chinese are
meant. We could add a feature gate just for Chinese and hope that it is the only
exception or have a more clever approach. Patches welcome, as I won't be able to
work on it.

**Comment by NullVerdict** [comment]
> I've researched the issue a bit again. I don't mind adding a mechanism for adding zh as an exception. However, I am not sure how to handle the ISO 639-3 to 639-1 conversion issue as zh would then translate both to zho and to cmn. While I see that mandarin is de facto what people refer to as `zh`, I still think it's wrong in specific scenarios, where the macro langauge, i.e. all Chinese are meant. We could add a feature gate just for Chinese and hope that it is the only exception or have a more clever approach. Patches welcome, as I won't be able to work on it.

You could do it this way, but I decided to do things differently in my project for now. Now I don't need to convert mandarin to ISO639-1. I solved this problem in a different way, without having to convert via any dependencies.
I think we can close the issue and forget about it.

**Comment by humenda** [comment]
>I think we can close the issue and forget about it. 

Alright, understood. In case you would like to pick it up at some point, I am
happy to take a PR, as I do see the need for this feature. It's just the open
question of handling ambiguities when converting zh to 639-1.
