### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aumetra** [humenda/isolang-rs#44]
The last release on crates.io is 6 months old by now and the main branch has since received two changes that would probably warrant a new release.

**Comment by humenda** [comment]
Have you been running the code for a while?

@djc Have you been running with (latest) master?

**Comment by djc** [comment]
Nope, I ended up not using isolang much in practice.

**Comment by humenda** [comment]
@djc Thanks anyway.

I would still wait a bit with the release and make it eventually next month,
waiting for any issues that might arise in the meantime.

**Comment by aumetra** [comment]
I've been running the latest master [here](https://github.com/kitsune-soc/kitsune) but it's not really a production environment by any means.  
If I hit any issues during that month, I'll report back here

**Comment by humenda** [comment]
The new version is out. Thanks go out to all contributors! :)
