### ISSUE TITLE
Error deserializing ISO 639-1 language codes

### ISSUE THREAD

**Issue by emk** [humenda/isolang-rs#7]
Hello! Thank you for creating an ISO 639-1 binding for Rust. It's great to have one. This will be very useful for my [subtitles-rs](https://github.com/emk/subtitles-rs) project.

Today, I noticed that when deserializing an `isolang::Language`, only 639-3 will be correctly parsed because of the call to `from_639_3`:

```rust
    fn visit_borrowed_str<E>(self, v: &'a str) -> Result<Self::Value, E>
            where E: serde::de::Error {
        match Language::from_639_3(v) {
            Some(l) => Ok(l),
            None => Err(serde::de::Error::unknown_variant(
                v,
                &["Any valid ISO 639-1 Code."],
            )),
        }
}
```

...but the error message says, `"Any valid ISO 639-1 Code."` This leads to some weird errors:

```
---- parse_metadata stdout ----
	thread 'parse_metadata' panicked at 'failed to parse example metadata: CouldNotParseMetadata { err: ErrorImpl { code: Message("unknown variant `fr`, expected `Any valid ISO 639-1 Code.`"), line: 7, column: 22 } }', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Perhaps the best solution would be to support deserializing both 639-1 and 639-3 codes?

Thank you for considering this issue!

**Comment by humenda** [comment]
This is a very clean solution, thanks for your work!

I'll publish a new version.

**Comment by emk** [comment]
Thank you for a very useful library!
